local_costmap:
  publish_voxel_map: true
  global_frame: odom
  robot_base_frame: base_link
  update_frequency: 10.0
  #5 - 10
  publish_frequency: 5.0
  #2.0 - 5
  static_map: false
  rolling_window: true
  width: 6.0
  height: 6.0
  resolution: 0.1
  #0.05
  inflation_radius: 0.80 
  #0.40

