// Auto-generated. Do not edit!

// (in-package turtlebot_actions.msg)


"use strict";

let _serializer = require('../base_serialize.js');
let _deserializer = require('../base_deserialize.js');
let _finder = require('../find.js');

//-----------------------------------------------------------

class TurtlebotMoveGoal {
  constructor() {
    this.turn_distance = 0.0;
    this.forward_distance = 0.0;
  }

  static serialize(obj, bufferInfo) {
    // Serializes a message object of type TurtlebotMoveGoal
    // Serialize message field [turn_distance]
    bufferInfo = _serializer.float32(obj.turn_distance, bufferInfo);
    // Serialize message field [forward_distance]
    bufferInfo = _serializer.float32(obj.forward_distance, bufferInfo);
    return bufferInfo;
  }

  static deserialize(buffer) {
    //deserializes a message object of type TurtlebotMoveGoal
    let tmp;
    let len;
    let data = new TurtlebotMoveGoal();
    // Deserialize message field [turn_distance]
    tmp = _deserializer.float32(buffer);
    data.turn_distance = tmp.data;
    buffer = tmp.buffer;
    // Deserialize message field [forward_distance]
    tmp = _deserializer.float32(buffer);
    data.forward_distance = tmp.data;
    buffer = tmp.buffer;
    return {
      data: data,
      buffer: buffer
    }
  }

  static datatype() {
    // Returns string type for a message object
    return 'turtlebot_actions/TurtlebotMoveGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'c971f114b08a2a1ad79af4c9ca9f358c';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #goal definition
    float32 turn_distance     # in radians, ccw = +, cw = -
    float32 forward_distance  # in meters, forward = +, backward = -
    
    `;
  }

};

module.exports = TurtlebotMoveGoal;
